[local_postgres_bronze.destination.postgres.credentials]
username = "postgres"
password = "admin"
host = "localhost"
port = 5432
database = "datalake_dlt"
sslmode = "disable"

[local_postgres_silver.destination.postgres.credentials]
username = "postgres"
password = "admin"
host = "localhost"
port = 5432
database = "datalake_dlt"
sslmode = "disable"

[local_postgres_gold.destination.postgres.credentials]
username = "postgres"
password = "admin"
host = "localhost"
port = 5432
database = "datalake_dlt"
sslmode = "disable"

[csv_to_postgres.destination.filesystem]
bucket_url = "C:/Users/diego.araujo/Desktop/DLTHUB/output"

[csv_to_postgres.credentials]
host = "dpg-d3og95je5dus73anodag-a.oregon-postgres.render.com"
port = 5432
username = "sales_data_system_user"
password = "VUBLVHWgTvFbBrhmIfEu0ktSkYm1Vvte"
database = "sales_data_system"
sslmode = true

[sources.mongodb.credentials]
uri = "mongodb://localhost:27017/"

[sources.api]
products_url = "https://raw.githubusercontent.com/diegooliveiradearaujo/api_json_dlt/refs/heads/main/json/product_api.json"
customers_url = "https://raw.githubusercontent.com/diegooliveiradearaujo/api_json_dlt/refs/heads/main/json/customer_api.json"

[sources.postgres_cloud.credentials]
username = "sales_data_system_user"
password = "VUBLVHWgTvFbBrhmIfEu0ktSkYm1Vvte"
host = "dpg-d3og95je5dus73anodag-a.oregon-postgres.render.com"
database = "sales_data_system"
sslmode = "require"
